spring:
  application:
    name: estudiantes

  # Configuración de MongoDB Atlas para WebFlux
  data:
    mongodb:
      uri: mongodb+srv://fockio94:PgjFLYVB0lya5uD7@cluster0.zjkoq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: colegio

  # Puerto en el que se ejecuta el microservicio
server:
  port: ${PORT:${SERVER_PORT:0}}

# Configuración de redis
redis:
  host: 127.0.0.1
  port: 6379

# Configuración de Eureka para el registro del servicio
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

resilience4j.circuitbreaker:
    instances:
      kafkaService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3