spring:
  application:
    name: kafka 

  # Puerto en el que se ejecuta el microservicio
server:
  port: ${PORT:${SERVER_PORT:0}}

# Configuración de Eureka para el registro del servicio
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
