server:
  port: 8888
spring:
  application:
   name: configserver
  banner:
    location: classpath:banner/banner.txt

  cloud:
   config:
    server:
     git:
      default-label: master
      uri: https://github.com/Portafolio-Proyectos-Microservicios/configserver.git
      search-paths: config-data
    enabled: true